export const mockWeatherData = {
  current: {
    condition: {
      code: 1189,
      icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
      text: 'Moderate rain',
    },
    feelslike_c: 10.5,
    gust_kph: 20.1,
    humidity: 82,
    temp_c: 12,
    uv: 3,
    wind_degree: 280,
    wind_dir: 'W',
    wind_kph: 11.2,
  },
  forecast: {
    forecastday: [
      {
        astro: {
          is_moon_up: 1,
          is_sun_up: 0,
          moon_illumination: 72,
          moon_phase: 'Waning Gibbous',
          moonrise: '08:25 PM',
          moonset: '01:22 PM',
          sunrise: '06:57 AM',
          sunset: '04:30 PM',
        },
        date: '2023-11-03',
        date_epoch: 1698969600,
        day: {
          avghumidity: 77,
          avgtemp_c: 9.6,
          avgtemp_f: 49.3,
          avgvis_km: 10,
          avgvis_miles: 6,
          condition: {
            text: 'Patchy rain possible',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063,
          },
          daily_chance_of_rain: 86,
          daily_chance_of_snow: 0,
          daily_will_it_rain: 1,
          daily_will_it_snow: 0,
          maxtemp_c: 12.3,
          maxtemp_f: 54.2,
          maxwind_kph: 25.9,
          maxwind_mph: 16.1,
          mintemp_c: 8.1,
          mintemp_f: 46.6,
          totalprecip_in: 0.01,
          totalprecip_mm: 0.36,
          totalsnow_cm: 0,
          uv: 2,
        },
        hour: [
          {
            time_epoch: 1698969600,
            time: '2023-11-03 00:00',
            temp_c: 9.8,
            temp_f: 49.6,
            is_day: 0,
            condition: {
              text: 'Some condition',
              icon: '//cdn.weatherapi.com/weather/64x64/day/123.png',
              code: 123,
            },
          },
          {
            time_epoch: 1698973200,
            time: '2023-11-03 01:00',
            temp_c: 9.5,
            temp_f: 49.0,
            is_day: 0,
            condition: {
              text: 'Condition 1',
              icon: '//cdn.weatherapi.com/weather/64x64/day/456.png',
              code: 456,
            },
          },
          {
            time_epoch: 1698976800,
            time: '2023-11-03 02:00',
            temp_c: 9.2,
            temp_f: 48.6,
            is_day: 0,
            condition: {
              text: 'Condition 2',
              icon: '//cdn.weatherapi.com/weather/64x64/day/789.png',
              code: 789,
            },
          },
          {
            time_epoch: 1698980400,
            time: '2023-11-03 03:00',
            temp_c: 9.0,
            temp_f: 48.2,
            is_day: 0,
            condition: {
              text: 'Condition 3',
              icon: '//cdn.weatherapi.com/weather/64x64/day/101.png',
              code: 101,
            },
          },
          {
            time_epoch: 1698984000,
            time: '2023-11-03 04:00',
            temp_c: 8.5,
            temp_f: 47.4,
            is_day: 0,
            condition: {
              text: 'Condition 4',
              icon: '//cdn.weatherapi.com/weather/64x64/day/112.png',
              code: 112,
            },
          },
        ],
      },
    ],
  },
  location: {
    country: 'United Kingdom',
    name: 'London',
    region: 'City of London, Greater London',
  },
};
